# Generated by Django 5.1.4 on 2025-01-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='暫無說明', verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(default='超值二手機', max_length=15, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.pmodel', verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=2016, verbose_name='出廠年份'),
        ),
    ]
