# Generated by Django 5.1.4 on 2025-01-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_product_description_alter_product_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pmodel',
        ),
        migrations.RemoveField(
            model_name='pphoto',
            name='product',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='不願意透漏身份的人', max_length=10)),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=10)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.mood')),
            ],
        ),
        migrations.DeleteModel(
            name='Maker',
        ),
        migrations.DeleteModel(
            name='PModel',
        ),
        migrations.DeleteModel(
            name='PPhoto',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
